import images from '../assets/images/images'

export default [
	{
		title: 'Push-Ups',
		exercises: [
			{
				title: 'Wall Push-Up',
				img: images.step1,
				mastery: {
					beginner: [1, 10],
					intermediate: [2, 25],
					master: [3, 50],
				},
				muscles: {
					pecs: 3,
					front_deltoids: 2,
					triceps: 2,
					biceps: 1,
				},
			},
			{
				title: 'Incline Push-Up',
				img: images.step2,
				mastery: {
					beginner: [1, 10],
					intermediate: [2, 20],
					master: [3, 40],
				},
				muscles: {
					pecs: 4,
					front_deltoids: 2,
					triceps: 2,
					biceps: 1,
				},
			},
			{ title: 'Kneeling Push-Up', img: images.step3 },
			{ title: 'Half Push-Up', img: images.step4 },
			{ title: 'Full Push-Up', img: images.step5 },
			{ title: 'Close Push-Up', img: images.step6 },
			{ title: 'Uneven Push-Up', img: images.step7 },
			{ title: 'Half One-Arm Push-Up', img: images.step8 },
			{ title: 'Lever Push-Up', img: images.step9 },
			{ title: 'One-Arm Push-Up', img: images.step10 },
		],
		img: images.step5,
	},
	{
		title: 'Pull-Ups',
		exercises: [
			{ title: 'Vertical Pull' },
			{ title: 'Horizontal Pull' },
			{ title: 'Jacknife Pull' },
			{ title: 'Half Pull-Up' },
			{ title: 'Full Pull-Up' },
			{ title: 'Close Pull-Up' },
			{ title: 'Uneven Pull-Up' },
			{ title: 'Half One-Arm Pull-Up' },
			{ title: 'Assisted Pull-Up' },
			{ title: 'One-Arm Pull-Up' },
		],
		img: images.pullups,
	},
	{
		title: 'Squats',
		exercises: [
			{ title: 'Shoulderstand Squat' },
			{ title: 'Jacknife Squat' },
			{ title: 'Supported Squat' },
			{ title: 'Half Squat' },
			{ title: 'Full Squat' },
			{ title: 'Close Squat' },
			{ title: 'Uneven Squat' },
			{ title: 'Half One-Leg Squat' },
			{ title: 'Assisted One-Leg Squat' },
			{ title: 'One-Leg Squat' },
		],
		img: images.squats,
	},
	{
		title: 'Leg Raises',
		exercises: [
			{ title: 'Knee Tuck' },
			{ title: 'Flat Knee Raise' },
			{ title: 'Flat Bent Leg Raise' },
			{ title: 'Flat Frog Raise' },
			{ title: 'Flat Straight Leg Raise' },
			{ title: 'Hanging Knee Raise' },
			{ title: 'Hanging Bent Leg Raise' },
			{ title: 'Hanging Frog Raise' },
			{ title: 'Partial Straight Leg Raise' },
			{ title: 'Hanging Straight Leg Raise' },
		],
		img: images.legraises,
	},
	{
		title: 'Handstand Push-Ups',
		exercises: [
			{ title: 'Wall Headstand' },
			{ title: 'Crow Stand' },
			{ title: 'Wall Handstand' },
			{ title: 'Half Handstand Push-Up' },
			{ title: 'Handstand Push-Up' },
			{ title: 'Close Handstand Push-Up' },
			{ title: 'Uneven Handstand Push-Up' },
			{ title: 'Half One-Arm Handstand Push-Up' },
			{ title: 'Lever Handstand Push-Up' },
			{ title: 'One-Arm Handstand Push-Up' },
		],
		img: images.handstandpu,
	},
	{
		title: 'Human flag',
		exercises: [
			{ title: 'Clutch Hang' },
			{ title: 'Diagonal Split Clutch' },
			{ title: 'Diagonal Tuck Clutch' },
			{ title: 'Diagonal Clutch' },
			{ title: 'Horizontal Tuck Clutch' },
			{ title: 'Horizontal Split Clutch' },
			{ title: 'Bent Leg Clutch Flag' },
			{ title: 'Clutch Flag' },
			{ title: 'Support Press' },
			{ title: 'Press Hang' },
			{ title: 'Kick Press' },
			{ title: 'Vertical Chamber Press' },
			{ title: 'Vertical Press' },
			{ title: 'Split Press Flag' },
			{ title: 'Bent Leg Press Flag' },
			{ title: 'Press Flag' },
		],
		img: images.humanflag,
	},
	{
		title: 'Planks',
		exercises: [
			{ title: 'Forearm Plank' },
			{ title: 'Straight Arm Plank' },
			{ title: 'Plank With Leg Raise' },
			{ title: 'One Leg Plank' },
			{ title: 'One Hand Plank' },
			{ title: 'One Hand One Leg Plank' },
			{ title: 'Forearm Side Plank' },
			{ title: 'Side Plank' },
			{ title: 'Forearm Back Plank' },
			{ title: 'Straight Arm Back Plank' },
			{ title: 'Back Plank With Leg Raise' },
		],
		img: images.planks,
	},
	{
		title: 'Dips',
		exercises: [
			{ title: 'Bent Leg Bench Dip' },
			{ title: 'Straight Leg Bench Dip' },
			{ title: 'Double Bench Dip' },
			{ title: 'Supported Parallel Bar Dip' },
			{ title: 'Parallel Bar Dip' },
			{ title: 'Straight Bar Dip' },
		],
		img: images.dips,
	},
	{
		title: 'Front Lever',
		exercises: [
			{ title: 'Tuck Front Lever' },
			{ title: 'Bent Leg Front Lever' },
			{ title: 'Split Bent Leg Front Lever' },
			{ title: 'One Leg Front Lever' },
			{ title: 'Advanced One Leg Front Lever' },
			{ title: 'Front Lever' },
		],
		img: images.frontlever,
	},
]
