export default {
  pecs: 'Pecs',
  biceps: 'Biceps',
  triceps: 'Triceps',
  front_deltoids: 'Front Deltoids',
  rotators: 'Rotator Cuffs',
  abs: 'Abs',
  traps: 'Traps',
  lats: 'Lats',
  back_deltoids: 'Rear Deltoids',
  rhomboids: 'Rhomboids',
  finger_flexors: 'Finger Flexors',
  teres: 'Teres',
  quadriceps: 'Quadriceps',
  hamstrings: 'Hamstrings',
  glutes: 'Glutes',
  shins: 'Shins',
  calves: 'Calves',
  flexors: 'Hip Flexors',
  pecs_minor: 'Pecs Minor',
  obliques: 'Obliques',
  serratus: 'Serratus',
  deltoids: 'Deltoids',
  erectors: 'Erectors',
  front_neck: 'Front Neck',
}
