import images from '../../assets/images/images'

export default [
  {
    title: 'Tuck Front Lever',
    img: images.frontlever_step1,
    mastery: {
      beginner: [1, '3 s'],
      intermediate: [1, '30 s'],
      master: [1, '60 s'],
    },
    muscles: {
      back_deltoids: 4,
      teres: 4,
      lats: 4,
      triceps: 4,
      rhomboids: 4,
      finger_flexors: 3,
      pecs: 3,
      front_neck: 2,
      obliques: 2,
      flexors: 1,
      abs: 1,
      quadriceps: 1,
      glutes: 1,
      erectors: 1,
    },
  },
  {
    title: 'Bent Leg Front Lever',
    img: images.frontlever_step2,
    mastery: {
      beginner: [1, '3 s'],
      intermediate: [1, '10 s'],
      master: [1, '30 s'],
    },
    muscles: {
      back_deltoids: 5,
      teres: 5,
      lats: 5,
      triceps: 5,
      rhomboids: 5,
      pecs: 4,
      finger_flexors: 3,
      obliques: 3,
      abs: 2,
      front_neck: 2,
      flexors: 2,
      erectors: 2,
      glutes: 1,
      quadriceps: 1,
    },
  },
  {
    title: 'Split Bent Leg Front Lever',
    img: images.frontlever_step3,
    mastery: {
      beginner: [1, '3 s'],
      intermediate: [1, '10 s'],
      master: [1, '30 s'],
    },
    muscles: {
      triceps: 5,
      back_deltoids: 5,
      teres: 5,
      lats: 5,
      rhomboids: 5,
      pecs: 5,
      flexors: 4,
      abs: 4,
      obliques: 4,
      erectors: 3,
      finger_flexors: 3,
      glutes: 3,
      quadriceps: 2,
      front_neck: 2,
    },
  },
  {
    title: 'One Leg Front Lever',
    img: images.frontlever_step4,
    mastery: {
      beginner: [1, '3 s'],
      intermediate: [1, '10 s'],
      master: [1, '30 s'],
    },
    muscles: {
      triceps: 5,
      teres: 5,
      abs: 5,
      obliques: 5,
      pecs: 5,
      rhomboids: 5,
      flexors: 5,
      lats: 5,
      back_deltoids: 5,
      erectors: 4,
      quadriceps: 4,
      glutes: 4,
      finger_flexors: 3,
      front_neck: 2,
    },
  },
  {
    title: 'Advanced One Leg Front Lever',
    img: images.frontlever_step5,
    mastery: {
      beginner: [1, '3 s'],
      intermediate: [1, '10 s'],
      master: [1, '30 s'],
    },
    muscles: {
      triceps: 5,
      teres: 5,
      abs: 5,
      obliques: 5,
      pecs: 5,
      rhomboids: 5,
      flexors: 5,
      lats: 5,
      back_deltoids: 5,
      glutes: 5,
      erectors: 4,
      quadriceps: 4,
      finger_flexors: 3,
      front_neck: 2,
    },
  },
  {
    title: 'Front Lever',
    img: images.frontlever_step6,
    mastery: {
      beginner: [1, '3 s'],
      intermediate: [1, '10 s'],
      master: [1, '30 s'],
    },
    muscles: {
      triceps: 5,
      teres: 5,
      abs: 5,
      obliques: 5,
      pecs: 5,
      rhomboids: 5,
      flexors: 5,
      lats: 5,
      back_deltoids: 5,
      glutes: 5,
      erectors: 5,
      quadriceps: 5,
      finger_flexors: 3,
      front_neck: 2,
    },
  },
]
