import images from '../../assets/images/images'

export default [
  {
    title: 'Wall Headstand',
    img: images.handstandpu_step1,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      traps: 3,
      rotators: 2,
      erectors: 2,
      triceps: 1,
    },
  },
  {
    title: 'Crow Stand',
    img: images.handstandpu_step2,
    mastery: {
      beginner: [1, '10 s'],
      intermediate: [1, '30 s'],
      master: [1, '60 s'],
    },
    muscles: {
      deltoids: 3,
      traps: 3,
      triceps: 3,
      finger_flexors: 3,
      serratus: 3,
      rotators: 2,
      pecs: 2,
    },
  },
  {
    title: 'Wall Handstand',
    img: images.handstandpu_step3,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      deltoids: 3,
      traps: 3,
      triceps: 3,
      finger_flexors: 3,
      lats: 2,
      erectors: 2,
      rotators: 2,
      glutes: 2,
    },
  },
  {
    title: 'Half Handstand Push-Up',
    img: images.handstandpu_step4,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 10],
      master: [2, 15],
    },
    muscles: {
      deltoids: 4,
      traps: 4,
      triceps: 4,
      finger_flexors: 3,
      rotators: 3,
      lats: 2,
      erectors: 2,
      glutes: 2,
      pecs_minor: 2,
    },
  },
  {
    title: 'Handstand Push-Up',
    img: images.handstandpu_step5,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 10],
      master: [2, 15],
    },
    muscles: {
      deltoids: 5,
      traps: 5,
      triceps: 5,
      finger_flexors: 4,
      rotators: 4,
      lats: 2,
      erectors: 2,
      glutes: 2,
      pecs: 2,
    },
  },
  {
    title: 'Close Handstand Push-Up',
    img: images.handstandpu_step6,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 9],
      master: [2, 12],
    },
    muscles: {
      deltoids: 5,
      traps: 5,
      triceps: 5,
      finger_flexors: 4,
      rotators: 4,
      lats: 2,
      erectors: 2,
      glutes: 2,
      pecs: 2,
    },
  },
  {
    title: 'Uneven Handstand Push-Up',
    img: images.handstandpu_step7,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 8],
      master: [2, 10],
    },
    muscles: {
      deltoids: 5,
      traps: 5,
      triceps: 5,
      rotators: 5,
      finger_flexors: 4,
      erectors: 3,
      lats: 2,
      glutes: 2,
      pecs: 2,
    },
  },
  {
    title: 'Half One-Arm Handstand Push-Up',
    img: images.handstandpu_step8,
    mastery: {
      beginner: [1, 4],
      intermediate: [2, 6],
      master: [2, 8],
    },
    muscles: {
      deltoids: 5,
      traps: 5,
      triceps: 5,
      finger_flexors: 4,
      rotators: 4,
      erectors: 3,
      lats: 2,
      glutes: 2,
      pecs: 2,
    },
  },
  {
    title: 'Lever Handstand Push-Up',
    img: images.handstandpu_step9,
    mastery: {
      beginner: [1, 3],
      intermediate: [2, 4],
      master: [2, 6],
    },
    muscles: {
      deltoids: 5,
      traps: 5,
      triceps: 5,
      finger_flexors: 4,
      rotators: 4,
      erectors: 3,
      lats: 2,
      glutes: 2,
      pecs: 2,
    },
  },
  {
    title: 'One-Arm Handstand Push-Up',
    img: images.handstandpu_step10,
    mastery: {
      beginner: [1, 1],
      intermediate: [2, 2],
      master: [1, 5],
    },
    muscles: {
      deltoids: 5,
      traps: 5,
      triceps: 5,
      finger_flexors: 4,
      rotators: 4,
      erectors: 3,
      lats: 2,
      glutes: 2,
      pecs: 2,
    },
  },
]
