import images from '../../assets/images/images'

export default [
  {
    title: 'Clutch Hang',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 2,
      obliques: 2,
      lats: 1,
      erectors: 1,
    },
  },
  {
    title: 'Diagonal Split Clutch',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 3,
      obliques: 3,
      lats: 2,
      biceps: 2,
    },
  },
  {
    title: 'Diagonal Tuck Clutch',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 3,
      obliques: 3,
      lats: 3,
      biceps: 3,
      erectors: 3,
    },
  },
  {
    title: 'Diagonal Clutch',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 4,
      obliques: 4,
      lats: 3,
      biceps: 3,
      erectors: 3,
    },
  },
  {
    title: 'Horizontal Tuck Clutch',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 4,
      obliques: 4,
      lats: 3,
      biceps: 3,
      erectors: 3,
    },
  },
  {
    title: 'Horizontal Split Clutch',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 4,
      obliques: 4,
      lats: 3,
      biceps: 3,
      erectors: 3,
    },
  },
  {
    title: 'Bent Leg Clutch Flag',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      serratus: 5,
      obliques: 5,
      lats: 4,
      biceps: 4,
      erectors: 4,
    },
  },
  {
    title: 'Clutch Flag',
    img: images.humanflag,
    mastery: {
      beginner: [1, '10 s'],
      intermediate: [1, '30 s'],
      master: [1, '60 s'],
    },
    muscles: {
      serratus: 5,
      obliques: 5,
      lats: 4,
      biceps: 4,
      erectors: 4,
    },
  },
  {
    title: 'Support Press',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      rotators: 3,
      lats: 2,
      erectors: 2,
      serratus: 2,
      biceps: 2,
      deltoids: 2,
      obliques: 2,
    },
  },
  {
    title: 'Press Hang',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      rotators: 3,
      obliques: 3,
      lats: 3,
      erectors: 3,
      serratus: 3,
      biceps: 3,
      deltoids: 3,
    },
  },
  {
    title: 'Kick Press',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      deltoids: 4,
      lats: 4,
      rotators: 4,
      obliques: 3,
      serratus: 3,
      erectors: 3,
      biceps: 3,
    },
  },
  {
    title: 'Vertical Chamber Press',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '3 s'],
      master: [1, '5 s'],
    },
    muscles: {
      deltoids: 4,
      lats: 4,
      rotators: 4,
      obliques: 4,
      serratus: 4,
      erectors: 4,
      biceps: 4,
    },
  },
  {
    title: 'Vertical Press',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '3 s'],
      master: [1, '5 s'],
    },
    muscles: {
      deltoids: 5,
      lats: 5,
      rotators: 5,
      obliques: 5,
      serratus: 5,
      erectors: 5,
      biceps: 5,
    },
  },
  {
    title: 'Split Press Flag',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '3 s'],
      master: [1, '5 s'],
    },
    muscles: {
      deltoids: 5,
      lats: 5,
      rotators: 5,
      obliques: 5,
      serratus: 5,
      erectors: 5,
      biceps: 5,
    },
  },
  {
    title: 'Bent Leg Press Flag',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '3 s'],
      master: [1, '5 s'],
    },
    muscles: {
      deltoids: 5,
      lats: 5,
      rotators: 5,
      obliques: 5,
      serratus: 5,
      erectors: 5,
      biceps: 5,
    },
  },
  {
    title: 'Press Flag',
    img: images.humanflag,
    mastery: {
      beginner: [1, '2 s'],
      intermediate: [1, '5 s'],
      master: [1, '10 s'],
    },
    muscles: {
      deltoids: 5,
      lats: 5,
      rotators: 5,
      obliques: 5,
      serratus: 5,
      erectors: 5,
      biceps: 5,
    },
  },
]
