import images from '../../assets/images/images'

export default [
  {
    title: 'Forearm Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      erectors: 5,
      abs: 5,
      quadriceps: 3,
      rhomboids: 3,
      rotators: 3,
      calves: 3,
      traps: 3,
      deltoids: 3,
      glutes: 3,
      pecs: 2,
      serratus: 2,
    },
  },
  {
    title: 'Straight Arm Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      abs: 4,
      erectors: 4,
      deltoids: 4,
      triceps: 3,
      quadriceps: 3,
      rotators: 3,
      calves: 3,
      traps: 3,
      glutes: 3,
      rhomboids: 3,
      pecs: 2,
      serratus: 2,
    },
  },
  {
    title: 'Plank With Leg Raise',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      erectors: 4,
      abs: 4,
      glutes: 4,
      deltoids: 4,
      quadriceps: 3,
      calves: 3,
      rotators: 3,
      serratus: 3,
      rhomboids: 3,
      triceps: 3,
      traps: 3,
      obliques: 3,
      pecs: 2,
    },
  },
  {
    title: 'One Leg Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      erectors: 5,
      abs: 5,
      glutes: 4,
      quadriceps: 4,
      calves: 4,
      deltoids: 3,
      rotators: 3,
      traps: 3,
      rhomboids: 3,
      pecs: 3,
      serratus: 2,
    },
  },
  {
    title: 'One Hand Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      erectors: 5,
      abs: 5,
      deltoids: 4,
      rhomboids: 4,
      traps: 4,
      rotators: 4,
      serratus: 3,
      pecs: 3,
      glutes: 3,
      quadriceps: 3,
      calves: 3,
    },
  },
  {
    title: 'One Hand One Leg Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      erectors: 5,
      abs: 5,
      traps: 4,
      glutes: 4,
      calves: 4,
      quadriceps: 4,
      rhomboids: 4,
      rotators: 4,
      deltoids: 4,
      serratus: 3,
      pecs: 3,
    },
  },
  {
    title: 'Forearm Side Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      obliques: 5,
      serratus: 4,
      deltoids: 4,
      abs: 3,
      erectors: 3,
      lats: 3,
      rotators: 3,
      quadriceps: 2,
      glutes: 2,
      hamstrings: 2,
    },
  },
  {
    title: 'Side Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      deltoids: 4,
      obliques: 4,
      lats: 3,
      rotators: 3,
      triceps: 3,
      serratus: 3,
      quadriceps: 2,
      abs: 2,
      erectors: 2,
      hamstrings: 2,
      glutes: 2,
    },
  },
  {
    title: 'Forearm Back Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      glutes: 5,
      erectors: 5,
      hamstrings: 3,
      calves: 3,
      deltoids: 2,
      abs: 2,
    },
  },
  {
    title: 'Straight Arm Back Plank',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      glutes: 4,
      erectors: 4,
      deltoids: 3,
      hamstrings: 3,
      calves: 3,
      triceps: 2,
      abs: 2,
    },
  },
  {
    title: 'Back Plank With Leg Raise',
    img: images.planks,
    mastery: {
      beginner: [1, '30 s'],
      intermediate: [1, '60 s'],
      master: [1, '120 s'],
    },
    muscles: {
      erectors: 4,
      glutes: 4,
      deltoids: 3,
      obliques: 3,
      hamstrings: 3,
      calves: 3,
      triceps: 2,
      abs: 2,
    },
  },
]
