import images from '../../assets/images/images'

export default [
  {
    title: 'Vertical Pull',
    img: images.pullup_step1,
    mastery: {
      beginner: [1, 10],
      intermediate: [2, 20],
      master: [3, 40],
    },
    muscles: {
      lats: 1,
      biceps: 1,
      traps: 1,
    },
  },
  {
    title: 'Horizontal Pull',
    img: images.pullup_step2,
    mastery: {
      beginner: [1, 10],
      intermediate: [2, 20],
      master: [3, 30],
    },
    muscles: {
      traps: 4,
      rhomboids: 2,
      back_deltoids: 2,
      biceps: 1,
    },
  },
  {
    title: 'Jacknife Pull',
    img: images.pullup_step3,
    mastery: {
      beginner: [1, 10],
      intermediate: [2, 15],
      master: [3, 20],
    },
    muscles: {
      lats: 4,
      rhomboids: 3,
      traps: 3,
      back_deltoids: 2,
      biceps: 3,
      pecs_minor: 2,
      finger_flexors: 2,
      teres: 2,
    },
  },
  {
    title: 'Half Pull-Up',
    img: images.pullup_step4,
    mastery: {
      beginner: [1, 8],
      intermediate: [2, 11],
      master: [2, 15],
    },
    muscles: {
      lats: 5,
      rhomboids: 3,
      traps: 3,
      back_deltoids: 3,
      biceps: 3,
      pecs_minor: 3,
      finger_flexors: 2,
      teres: 2,
    },
  },
  {
    title: 'Full Pull-Up',
    img: images.pullup_step5,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 8],
      master: [2, 10],
    },
    muscles: {
      lats: 5,
      rhomboids: 4,
      traps: 4,
      back_deltoids: 4,
      biceps: 4,
      pecs_minor: 3,
      finger_flexors: 3,
      teres: 3,
    },
  },
  {
    title: 'Close Pull-Up',
    img: images.pullup_step6,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 8],
      master: [2, 10],
    },
    muscles: {
      biceps: 5,
      lats: 4,
      rhomboids: 4,
      traps: 4,
      back_deltoids: 4,
      pecs_minor: 3,
      finger_flexors: 3,
      teres: 3,
    },
  },
  {
    title: 'Uneven Pull-Up',
    img: images.pullup_step7,
    mastery: {
      beginner: [1, 5],
      intermediate: [2, 7],
      master: [2, 9],
    },
    muscles: {
      biceps: 5,
      lats: 4,
      rhomboids: 4,
      traps: 4,
      back_deltoids: 4,
      pecs_minor: 3,
      finger_flexors: 3,
      teres: 3,
    },
  },
  {
    title: 'Half One-Arm Pull-Up',
    img: images.pullup_step8,
    mastery: {
      beginner: [1, 4],
      intermediate: [2, 6],
      master: [2, 8],
    },
    muscles: {
      biceps: 5,
      lats: 4,
      rhomboids: 4,
      traps: 4,
      back_deltoids: 4,
      pecs_minor: 3,
      finger_flexors: 3,
      teres: 3,
    },
  },
  {
    title: 'Assisted Pull-Up',
    img: images.pullup_step9,
    mastery: {
      beginner: [1, 3],
      intermediate: [2, 5],
      master: [2, 7],
    },
    muscles: {
      biceps: 5,
      lats: 4,
      rhomboids: 4,
      traps: 4,
      back_deltoids: 4,
      pecs_minor: 3,
      finger_flexors: 3,
      teres: 3,
    },
  },
  {
    title: 'One-Arm Pull-Up',
    img: images.pullup_step10,
    mastery: {
      beginner: [1, 1],
      intermediate: [2, 3],
      master: [2, 6],
    },
    muscles: {
      biceps: 5,
      lats: 5,
      rhomboids: 4,
      traps: 4,
      back_deltoids: 4,
      finger_flexors: 4,
      pecs_minor: 3,
      teres: 3,
    },
  },
]
